### ISSUE TITLE
Ensure one top-level class per file to avoid unpredictable behavior

### ISSUE THREAD

**Issue by suyeon-jung-dev** [litmuschaos/litmus-java-sdk#14]
Currently, we have 2 top-level classes in CapabilityResponse.java single source file. We need to refactor `Dex` class to inner class in CapabilityResponse.java. According to best practices, only one top-level class should be defined per file. This is because, 

- When multiple top-level classes are defined in a single file, the compiler does not guarantee the order in which they are compiled. so this can result in different execution behavior each time the code is compiled, depending on how the classes (CapabilityResponse and Dex) are loaded by the JVM.
- Seperating the multiple top-level classes to single top-level classes can maintain code clarity and readability.

And you can check item 25 in Effective Java 3rd Edition by Joshua Bloch.

https://github.com/litmuschaos/litmus-java-sdk/blob/3d148dc80dc959decab4468f08bfc1278de32f27/src/main/java/io/litmuschaos/response/CapabilityResponse.java#L3-L16

**Comment by seedspirit** [comment]
solved this issue in below commit

https://github.com/litmuschaos/litmus-java-sdk/pull/21/commits/40418ae71b5e64e9afd6476b5c59f0f8ff851b1a
