### ISSUE TITLE
Add methods about users in auth-server in litmus

### ISSUE THREAD

**Issue by suyeon-jung-dev** [litmuschaos/litmus-java-sdk#5]
We need to add methods wrapped user APIs in auth-server.

- users
- getuser
- updatePassword
- createUser
- resetPassword
- updateDetails
- updateState

The auth-server documentation is [here](https://github.com/litmuschaos/litmus/blob/master/mkdocs/docs/auth/v3.9.0/auth-api.json)

**Comment by seedspirit** [comment]
Can I take this issue?
